package com.spring.movie.dtos;
// Generated 19 Aug, 2020 1:51:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblMoviesInfo generated by hbm2java
 */
@Entity
@Table(name="tbl_movies_info"
    ,catalog="db_movies"
)
public class TblMoviesInfo  implements java.io.Serializable {


     private Integer id;
     private String category;
     private String title;
     private double rating;
     private boolean status;
     private Date addedDate;

    public TblMoviesInfo() {
    }

    public TblMoviesInfo(String category, String title, double rating, boolean status, Date addedBy) {
       this.category = category;
       this.title = title;
       this.rating = rating;
       this.status = status;
       this.addedDate = addedBy;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

  
    
    @Column(name="category", nullable=false, length=100)
	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name="title", nullable=false, length=100)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="rating", nullable=false, precision=22, scale=0)
    public double getRating() {
        return this.rating;
    }
    
    public void setRating(double rating) {
        this.rating = rating;
    }

    
    @Column(name="status", nullable=false)
    public boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="added_date", nullable=false, length=19)
    public Date getAddedDate() {
        return this.addedDate;
    }
    
    public void setAddedDate(Date addedBy) {
        this.addedDate = addedBy;
    }




}


